<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- This is the target framework; we are using .NET 10.0, which is the latest version of .NET. -->
    <TargetFramework>net10.0</TargetFramework>
    <!-- Whenever you use a reference type, you have to specify whether it can be null or not. -->
    <Nullable>enable</Nullable>
    <!-- This enables implicit using directives, so you don't have to manually add common namespaces. -->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
